version: "3.8"

services:
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - evolution_redis
      - evolution_postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  evolution_frontend:
    container_name: evolution_frontend
    image: atendai/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    environment:
      - SERVER_URL=http://evolution_api:8080
      - GLOBAL_API_KEY=429683C4C977415CAAFCCE10F7D57E11
    networks:
      - evolution-net

  evolution_redis:
    container_name: evolution_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    expose:
      - "6379"
    networks:
      - evolution-net

  evolution_postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge