services:
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.7
    restart: always
    depends_on:
      - evolution_redis
      - evolution_postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_PROVIDER=postgres
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@evolution_postgres:5432/${POSTGRES_DATABASE}?schema=public
      - CACHE_REDIS_URI=redis://evolution_redis:6379/6
      - SERVER_PORT=8080
      - SERVER_URL=http://161.132.37.52:8080
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  evolution_frontend:
    container_name: evolution_frontend
    image: atendai/evolution-manager:latest
    restart: always
    depends_on:
      - evolution_api
    ports:
      - "3000:80"
    environment:
      - SERVER_URL=http://161.132.37.52:8080
      - GLOBAL_API_KEY=${AUTHENTICATION_API_KEY}
    networks:
      - evolution-net

  evolution_redis:
    container_name: evolution_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    expose:
      - "6379"
    networks:
      - evolution-net

  evolution_postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
